spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/library
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  spring:
    jackson:
      deserialization:
        fail-on-unknown-properties: false
server:
  port: 8080
